import io
import logging
import os
import re
import time
import zipfile
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests
from flask import Flask, jsonify, request, send_file, send_from_directory

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FRONTEND_DIR = os.path.join(BASE_DIR, "..", "frontend")
EXTENSION_DIR = os.path.join(BASE_DIR, "..", "extension")
app = Flask(__name__, static_folder=FRONTEND_DIR, static_url_path="")

# gunicorn配下ではFlaskのapp.loggerに出力先が付かず、WARNING未満が捨てられる。
# gunicornのエラーロガーに相乗りさせて、INFOをjournalへ流す。
_gunicorn_logger = logging.getLogger("gunicorn.error")
if _gunicorn_logger.handlers:
    app.logger.handlers = _gunicorn_logger.handlers
    app.logger.setLevel(_gunicorn_logger.level or logging.INFO)
else:
    logging.basicConfig(level=logging.INFO)
    app.logger.setLevel(logging.INFO)

NOTE_API_BASE = "https://note.com/api/v2/creators"
NOTE_FOLLOW_API_BASE = "https://note.com/api/v3/users"
REQUEST_HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; YouMitonde/1.0)"}
REQUEST_TIMEOUT = 10
MAX_WORKERS = 3  # note.comの前段CloudFrontは同時接続が多いほど403を返しやすい。速度より通ることを優先する
MAX_FOLLOW_LIST_ITEMS = 20000  # safety cap against accidental/huge account lists, in items (not pages --
# note.com's actual per-page size for these endpoints is undocumented and has changed before, so a fixed
# page-count cap silently turns into a much lower item cap whenever the real page size is smaller than assumed)
FOLLOW_LIST_PAGE_SIZE_PARAM = 100  # passing &per= at all lifts note.com's ~600-item cap on these lists
# note.com自身のWeb UIが使う値。ここを増やしてはいけない。
# 2026-08-21に per=100 を試したところ、v3は 200 を返しながら中身を空で返し、
# 一覧が丸ごと0件になった（エラーにならないためフォールバックも効かない）。
# 公開v2では per を渡すと上限が緩むが、v3では同じ手が通用しない。
NOTE_V3_USER_LIST_PAGE_SIZE = 20
FOLLOW_ACTION_DELAY_SECONDS = 4.0  # note.com 429s a burst of follow/unfollow calls; space them out
# (CloudFront in front of note.com has also been observed to hard-block this server's IP entirely
# after ~20 sequential follow/unfollow calls at the old 2.5s spacing -- see is_cloudfront_block_response)
CLOUDFRONT_BLOCK_MARKERS = (
    "The request could not be satisfied",
    "Generated by cloudfront",
    "Request blocked",
)
MAX_FOLLOW_ACTION_TARGETS = 200  # guard against accidental/huge batch requests
AUTH_VERIFY_WORKERS = 4
RATE_LIMIT_RETRY_DELAYS_SECONDS = (1.0, 2.0)
RATE_LIMIT_RETRY_AFTER_SECONDS = 90
RATE_LIMIT_ERROR_MESSAGE = (
    "note.comのレート制限にかかっています。フォロー操作の直後は一覧取得が制限されることがあるため、"
    "1〜2分ほど待ってから再チェックしてください。"
)
RETRYABLE_STATUS_CODES = (403, 429, 502, 503, 504)
# 403は「CloudFrontのハードブロック」と「一時的に弾かれただけ」の2種類がある。
# 後者は少し待って投げ直すと通ることが多いのでリトライし、前者は待っても無駄な上に
# 叩き続けるとブロックが延びるため、request_with_retriesの中で即座に打ち切る。
SERVER_BUSY_ERROR_MESSAGE = "note.comが一時的に混み合っているようです。少し待ってから再度お試しください。"


class NoteApiError(Exception):
    def __init__(self, message, status=502, retry_after=None):
        super().__init__(message)
        self.message = message
        self.status = status
        self.retry_after = retry_after


def normalize_username(raw):
    raw = raw.strip()
    raw = re.sub(r"^https?://(www\.)?note\.com/", "", raw)
    raw = raw.lstrip("@")
    raw = raw.strip("/")
    raw = raw.split("/")[0].split("?")[0]
    return raw


def request_headers(cookie_header=None):
    headers = {**REQUEST_HEADERS}
    if cookie_header:
        headers["Cookie"] = cookie_header
    return headers


def parse_retry_after(raw):
    if not raw:
        return RATE_LIMIT_RETRY_AFTER_SECONDS
    try:
        return max(1, int(float(raw)))
    except (TypeError, ValueError):
        return RATE_LIMIT_RETRY_AFTER_SECONDS


def note_error_response(exc):
    payload = {"error": exc.message}
    if exc.retry_after:
        payload["retryAfterSeconds"] = exc.retry_after
    response = jsonify(payload)
    if exc.retry_after:
        response.headers["Retry-After"] = str(exc.retry_after)
    return response, exc.status


def note_json(resp, context):
    try:
        data = resp.json()
    except ValueError:
        raise NoteApiError(
            f"{context}の応答を読み取れませんでした。note.comが一時的に制限している可能性があるため、少し待ってから再チェックしてください。"
        )

    if not isinstance(data, dict):
        raise NoteApiError(
            f"{context}の応答形式が想定外でした。時間をおいてもう一度お試しください。"
        )
    return data


def request_with_retries(session, url, params=None, headers=None):
    resp = None
    for delay in (0, *RATE_LIMIT_RETRY_DELAYS_SECONDS):
        if delay:
            time.sleep(delay)
        resp = session.get(url, params=params, headers=headers or REQUEST_HEADERS, timeout=REQUEST_TIMEOUT)
        if resp.status_code not in RETRYABLE_STATUS_CODES:
            break
        if resp.status_code == 403 and is_cloudfront_block_response(resp):
            # ハードブロック中。投げ直しても通らず、ブロック期間を延ばすだけ。
            break
    return resp


def is_cloudfront_block_response(resp):
    # A generic CloudFront error page (not a note.com application response),
    # returned once this server's requests get hard-blocked for a while.
    #
    # Detection used to look for one phrase in the first 500 characters of the
    # body only, which missed blocks whose page starts with a longer <head> or
    # uses different wording -- those surfaced to the user as the unhelpful
    # "status 403" message instead of the "wait 30-60 minutes" one. The X-Cache
    # header is the reliable signal (CloudFront sets it when *it* generated the
    # error, not note.com), with the body markers kept as a fallback.
    if "error from cloudfront" in (resp.headers.get("X-Cache") or "").lower():
        return True
    body = (resp.text or "")[:4000].lower()
    return any(marker.lower() in body for marker in CLOUDFRONT_BLOCK_MARKERS)


def raise_for_transient_status(resp):
    if resp.status_code == 429:
        raise NoteApiError(
            RATE_LIMIT_ERROR_MESSAGE,
            status=429,
            retry_after=parse_retry_after(resp.headers.get("Retry-After")),
        )
    if resp.status_code == 403 and is_cloudfront_block_response(resp):
        raise NoteApiError(
            "note.com側のアクセス制限（一時的なブロック）にかかっています。"
            "30分〜1時間ほど間隔を空けてから再度お試しください。",
            status=403,
            retry_after=RATE_LIMIT_RETRY_AFTER_SECONDS,
        )
    if resp.status_code in (502, 503, 504):
        raise NoteApiError(SERVER_BUSY_ERROR_MESSAGE, status=503, retry_after=RATE_LIMIT_RETRY_AFTER_SECONDS)


def fetch_creator(session, urlname, headers=None):
    resp = request_with_retries(session, f"{NOTE_API_BASE}/{urlname}", headers=headers)
    if resp.status_code == 404:
        return None
    raise_for_transient_status(resp)
    if resp.status_code != 200:
        raise NoteApiError(f"note.comへの問い合わせに失敗しました（status {resp.status_code}）")
    return note_json(resp, "note.com").get("data")


def fetch_follow_page(session, urlname, kind, page):
    resp = request_with_retries(
        session,
        f"{NOTE_API_BASE}/{urlname}/{kind}",
        params={"page": page, "per": FOLLOW_LIST_PAGE_SIZE_PARAM},
    )
    raise_for_transient_status(resp)
    if resp.status_code != 200:
        raise NoteApiError(f"{kind}の取得に失敗しました（status {resp.status_code}）")
    data = note_json(resp, kind).get("data")
    if isinstance(data, list):
        # note.com returns {"data": []} instead of the usual object shape
        # once a list is empty or a page is requested past the end.
        return [], 0, True
    if not isinstance(data, dict):
        raise NoteApiError(
            f"{kind}の応答形式が想定外でした。時間をおいてもう一度お試しください。"
        )
    return data.get("follows", []), data.get("totalCount", 0), data.get("isLastPage", True)


FOLLOW_PAGE_RETRY_BACKOFF_SECONDS = (1.0, 3.0, 6.0)  # extra retries for a single page within a bulk fetch


def fetch_follow_page_resilient(session, urlname, kind, page):
    # A bulk fetch spanning many pages (e.g. 1000+ followers needs ~50 requests
    # at FOLLOW_LIST_PAGE_SIZE_PARAM items each) is far more likely to have at
    # least one page transiently fail than a single request is. fetch_follow_page
    # already retries transient statuses a couple of times with short delays;
    # this adds a slower outer retry so one flaky page doesn't abort the whole
    # list and make it look like the account "can't be fetched" once it grows
    # past a few hundred follows/followers.
    last_error = None
    for delay in (0.0, *FOLLOW_PAGE_RETRY_BACKOFF_SECONDS):
        if delay:
            time.sleep(delay)
        try:
            return fetch_follow_page(session, urlname, kind, page)
        except NoteApiError as exc:
            last_error = exc
    raise last_error


def fetch_all_follows(session, urlname, kind):
    follows, total, is_last = fetch_follow_page_resilient(session, urlname, kind, 1)
    if is_last or not follows:
        return follows, total

    page_size = len(follows)
    max_pages = max(1, -(-MAX_FOLLOW_LIST_ITEMS // page_size))  # ceil division, item-count safety cap
    results = {1: follows}

    def worker(page):
        time.sleep(0.05)
        return fetch_follow_page_resilient(session, urlname, kind, page)

    # note.com's reported totalCount for these lists has been wrong/capped
    # before (independently of any pagination trick -- see the 600-item-cap
    # fix above), so it's only used to size the first parallel batch of
    # requests. The real stopping condition is each page's own isLastPage
    # flag (or an empty page), never a page count derived from totalCount --
    # otherwise a stale/capped totalCount silently truncates the whole list
    # even though more pages genuinely exist.
    next_page = 2
    wave_end = min(max(-(-total // page_size), next_page), max_pages)
    reached_end = False

    while next_page <= max_pages and not reached_end:
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = {executor.submit(worker, page): page for page in range(next_page, wave_end + 1)}
            for future in as_completed(futures):
                page = futures[future]
                items, _, page_is_last = future.result()
                results[page] = items
                if page_is_last or not items:
                    reached_end = True
        next_page = wave_end + 1
        wave_end = min(next_page + MAX_WORKERS - 1, max_pages)

    all_follows = []
    for page in sorted(results):
        all_follows.extend(results[page])
    return all_follows, max(total, len(all_follows))


# NOTE_API_BASE (/api/v2/creators/{urlname}/followers|followings) is the public,
# unauthenticated endpoint and has its own undocumented item cap (originally 600,
# now observed at ~1000) that the `per` param workaround above does not lift.
# When the request is authenticated as the very account being checked (the
# common case: a user checking their own follow lists), note.com's own web UI
# instead calls /api/v3/users/{key}/followers|followings -- the same
# NOTE_FOLLOW_API_BASE family already used for follow/unfollow -- which returns
# the real, uncapped total. Its response shape uses snake_case fields
# (total_count / is_last_page), unlike the v2 endpoint's camelCase.
def fetch_follow_page_v3(session, key, kind, page, cookie_header, per=NOTE_V3_USER_LIST_PAGE_SIZE):
    headers = {
        **REQUEST_HEADERS,
        "X-Requested-With": "XMLHttpRequest",
        "Cookie": cookie_header,
    }
    resp = request_with_retries(
        session,
        f"{NOTE_FOLLOW_API_BASE}/{key}/{kind}",
        params={"page": page, "per": per},
        headers=headers,
    )
    raise_for_transient_status(resp)
    if resp.status_code != 200:
        raise NoteApiError(f"{kind}の取得に失敗しました（status {resp.status_code}）")
    data = note_json(resp, kind).get("data")
    if isinstance(data, list):
        return [], 0, True
    if not isinstance(data, dict):
        raise NoteApiError(
            f"{kind}の応答形式が想定外でした。時間をおいてもう一度お試しください。"
        )
    return data.get("follows", []), data.get("total_count", 0), data.get("is_last_page", True)


def fetch_follow_page_v3_resilient(
    session, key, kind, page, cookie_header, per=NOTE_V3_USER_LIST_PAGE_SIZE
):
    last_error = None
    for delay in (0.0, *FOLLOW_PAGE_RETRY_BACKOFF_SECONDS):
        if delay:
            time.sleep(delay)
        try:
            return fetch_follow_page_v3(session, key, kind, page, cookie_header, per)
        except NoteApiError as exc:
            last_error = exc
    raise last_error



def fetch_all_follows_v3(session, key, kind, cookie_header):
    per = NOTE_V3_USER_LIST_PAGE_SIZE
    follows, total, is_last = fetch_follow_page_v3_resilient(session, key, kind, 1, cookie_header, per)
    if is_last or not follows:
        return follows, total

    page_size = len(follows)
    max_pages = max(1, -(-MAX_FOLLOW_LIST_ITEMS // page_size))
    results = {1: follows}

    def worker(page):
        time.sleep(0.05)
        return fetch_follow_page_v3_resilient(session, key, kind, page, cookie_header, per)

    next_page = 2
    wave_end = min(max(-(-total // page_size), next_page), max_pages)
    reached_end = False

    while next_page <= max_pages and not reached_end:
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = {executor.submit(worker, page): page for page in range(next_page, wave_end + 1)}
            for future in as_completed(futures):
                page = futures[future]
                items, _, page_is_last = future.result()
                results[page] = items
                if page_is_last or not items:
                    reached_end = True
        next_page = wave_end + 1
        wave_end = min(next_page + MAX_WORKERS - 1, max_pages)

    all_follows = []
    for page in sorted(results):
        all_follows.extend(results[page])
    # note.comが申告する総数に届いたかどうかで、上限に当たったかが分かる。
    # perを上げた効果を後から確かめるために残す。
    app.logger.info(
        "v3の%s: per=%sで%s件取得（total_count=%s、%s）",
        kind,
        per,
        len(all_follows),
        total,
        "全件" if total and len(all_follows) >= total else "途中で打ち切られた",
    )
    return all_follows, max(total, len(all_follows))


def to_account(entry):
    urlname = entry.get("urlname")
    return {
        "key": entry.get("key"),
        "urlname": urlname,
        "name": entry.get("nickname") or entry.get("name") or urlname,
        # v2 (/api/v2/creators/.../followers) uses camelCase; v3
        # (/api/v3/users/.../followers) uses snake_case for the same field.
        "profileImage": entry.get("userProfileImagePath") or entry.get("user_profile_image_path"),
        "noteUrl": f"https://note.com/{urlname}",
    }


def normalized_urlname(entry):
    urlname = entry.get("urlname")
    if not urlname:
        return None
    return str(urlname).strip().lower()


def account_identity_values(entry):
    identities = set()
    for field in ("key", "id"):
        value = entry.get(field)
        if value:
            identities.add((field, str(value)))

    urlname = normalized_urlname(entry)
    if urlname:
        identities.add(("urlname", urlname))

    return identities


def account_identities(entries):
    identities = set()
    for entry in entries:
        identities.update(account_identity_values(entry))
    return identities


def is_known_account(entry, identities):
    return not account_identity_values(entry).isdisjoint(identities)


def parse_check_request():
    if request.method == "POST":
        payload = request.get_json(silent=True) or {}
        return normalize_username(payload.get("username", "")), (payload.get("cookieHeader") or "").strip()

    return normalize_username(request.args.get("username", "")), ""


def cookie_matches_creator(session, urlname, cookie_header):
    if not cookie_header:
        return False

    try:
        creator = fetch_creator(session, urlname, headers=request_headers(cookie_header))
    except (NoteApiError, requests.RequestException):
        return False

    return bool(creator and creator.get("isMyself"))


def refine_accounts_with_authenticated_state(session, accounts, cookie_header, keep_account):
    if not accounts:
        return accounts

    headers = request_headers(cookie_header)

    def worker(account):
        try:
            detail = fetch_creator(session, account["urlname"], headers=headers)
        except (NoteApiError, requests.RequestException):
            return account

        if detail is None:
            # note.com returned 404 for this account: it's been deleted/withdrawn
            # or otherwise no longer exists, so drop it instead of showing it.
            return None

        return account if keep_account(detail) else None

    refined = []
    with ThreadPoolExecutor(max_workers=AUTH_VERIFY_WORKERS) as executor:
        futures = [executor.submit(worker, account) for account in accounts]
        for future in as_completed(futures):
            account = future.result()
            if account:
                refined.append(account)

    refined.sort(key=lambda account: account["name"])
    return refined


@app.get("/api/creator/<urlname>")
def creator_detail(urlname):
    session = requests.Session()
    try:
        creator = fetch_creator(session, urlname)
    except NoteApiError as exc:
        return note_error_response(exc)
    except requests.RequestException:
        return jsonify({"error": "note.comへの接続に失敗しました。時間をおいてもう一度お試しください"}), 502

    if creator is None:
        return jsonify({"error": f"ユーザー「{urlname}」が見つかりませんでした"}), 404

    return jsonify(
        {
            "urlname": creator.get("urlname"),
            "name": creator.get("nickname"),
            "profile": creator.get("profile"),
            "profileImage": creator.get("profileImageUrl"),
            "followingCount": creator.get("followingCount") or 0,
            "followerCount": creator.get("followerCount") or 0,
            "noteCount": creator.get("noteCount") or 0,
        }
    )


@app.route("/api/check", methods=["GET", "POST"])
def check():
    urlname, cookie_header = parse_check_request()
    if not urlname:
        return jsonify({"error": "noteのユーザー名を入力してください"}), 400
    if not cookie_header:
        return jsonify({"error": "アカウントチェックにはnote.comのCookie文字列が必要です"}), 400

    session = requests.Session()
    try:
        creator = fetch_creator(session, urlname)
        if creator is None:
            return jsonify({"error": f"ユーザー「{urlname}」が見つかりませんでした"}), 404

        authenticated_check = cookie_matches_creator(session, urlname, cookie_header)
        creator_key = creator.get("key")
        if authenticated_check and creator_key:
            # The public v2/creators endpoint has its own undocumented item
            # cap that the `per` param doesn't lift. When checking your own
            # account (the common case here), note.com's own web UI instead
            # calls this authenticated v3 endpoint, which returns the real,
            # uncapped total.
            followings, followings_total = fetch_all_follows_v3(session, creator_key, "followings", cookie_header)
            followers, followers_total = fetch_all_follows_v3(session, creator_key, "followers", cookie_header)
        else:
            followings, followings_total = fetch_all_follows(session, urlname, "followings")
            followers, followers_total = fetch_all_follows(session, urlname, "followers")
    except NoteApiError as exc:
        return note_error_response(exc)
    except requests.RequestException:
        return jsonify({"error": "note.comへの接続に失敗しました。時間をおいてもう一度お試しください"}), 502

    follower_identities = account_identities(followers)
    follower_count = creator.get("followerCount") or 0
    following_count = creator.get("followingCount") or 0
    # 上限判定は2種類ある。どちらか一方でも当てはまれば「全部は見られていない」。
    #   (1) note.comが申告する総数そのものが頭打ちになっている（公開v2の~1000件上限）
    #   (2) 総数は正しいのに、一覧が途中で打ち切られて取り切れていない
    # (2)を見ていなかったため、認証済みv3が「総数1629」と正しく返しつつ実際には
    # 1000件しか返さないケースを「全部取れた」と誤判定し、1000件中の結果を
    # 1629件中の結果であるかのように表示していた。
    followers_capped = (follower_count > 0 and follower_count > followers_total) or (
        followers_total > 0 and len(followers) < followers_total
    )
    followings_capped = (following_count > 0 and following_count > followings_total) or (
        followings_total > 0 and len(followings) < followings_total
    )
    auth_warning = None
    to_follow_back_unavailable_reason = None

    not_following_back_scope = None
    if authenticated_check:
        # 各アカウントのisFollowedを直接見る方式。フォロワー一覧の取得状況に
        # 依存しないため、フォロー中一覧が途中までしか取れていない場合でも、
        # 取れた範囲については正しい結果になる。範囲だけ利用者に伝える。
        not_following_back = refine_accounts_with_authenticated_state(
            session,
            [to_account(f) for f in followings],
            cookie_header,
            lambda detail: not detail.get("isFollowed"),
        )
        not_following_back_reliable = not followings_capped
        if followings_capped:
            not_following_back_scope = (
                f"フォロー中{following_count:,}人のうち、note.com側の上限で確認できた"
                f"{len(followings):,}人の中での結果です。"
            )
    elif followers_capped:
        not_following_back = []
        not_following_back_reliable = False
    else:
        not_following_back = [
            to_account(f) for f in followings if not is_known_account(f, follower_identities)
        ]
        not_following_back.sort(key=lambda account: account["name"])
        not_following_back_reliable = True

    if authenticated_check and not followers_capped:
        to_follow_back = refine_accounts_with_authenticated_state(
            session,
            [to_account(f) for f in followers],
            cookie_header,
            lambda detail: not detail.get("isFollowing"),
        )
    elif cookie_header and not authenticated_check:
        to_follow_back = []
        auth_warning = "Cookieのログインアカウントとチェック対象が一致しなかったため、フォロー済みかどうかの追加確認は使いませんでした。"
        to_follow_back_unavailable_reason = auth_warning
    elif followers_capped:
        to_follow_back = []
        to_follow_back_unavailable_reason = "フォロワー一覧がnote.com側の上限で一部しか取得できないため、フォロー返し候補は正確に判定できません。"
    else:
        to_follow_back = []
        to_follow_back_unavailable_reason = "フォロー返し候補は、Cookieを貼ってログイン中の本人として確認できた場合だけ表示します。Cookieを入力して再チェックしてください。"

    capped = followers_capped or followings_capped

    # 画面の数字（note.comのプロフィールカウンター）と、実際に突き合わせた件数の
    # ズレを追うための記録。プロフィールの数字と、こちらが取得できた一覧の件数と、
    # 片思い判定の結果が別ソースになるため、食い違ったときはここを見る。
    app.logger.info(
        "check urlname=%s auth=%s プロフィール(following=%s follower=%s) "
        "取得(following=%s follower=%s) total(following=%s follower=%s) "
        "capped(following=%s follower=%s) 片思い=%s フォロー返し候補=%s",
        urlname,
        authenticated_check,
        following_count,
        follower_count,
        len(followings),
        len(followers),
        followings_total,
        followers_total,
        followings_capped,
        followers_capped,
        len(not_following_back),
        len(to_follow_back),
    )

    return jsonify(
        {
            "creator": {
                "urlname": creator.get("urlname"),
                "name": creator.get("nickname"),
                "profileImage": creator.get("profileImageUrl"),
                "followingCount": following_count,
                "followerCount": follower_count,
            },
            "checkedFollowingCount": len(followings),
            "checkedFollowerCount": len(followers),
            "notFollowingBack": not_following_back,
            "toFollowBack": to_follow_back,
            "notFollowingBackReliable": not_following_back_reliable,
            "notFollowingBackScope": not_following_back_scope,
            "toFollowBackReliable": authenticated_check and not followers_capped,
            "toFollowBackUnavailableReason": to_follow_back_unavailable_reason,
            "authenticatedCheck": authenticated_check,
            "authWarning": auth_warning,
            "capped": capped,
        }
    )


def parse_follow_action_request():
    payload = request.get_json(silent=True) or {}
    cookie_header = (payload.get("cookieHeader") or "").strip()
    targets = payload.get("targets") or []

    if not cookie_header:
        return None, None, (jsonify({"error": "note.comのCookie文字列を入力してください"}), 400)
    if not targets:
        return None, None, (jsonify({"error": "対象が選択されていません"}), 400)
    if len(targets) > MAX_FOLLOW_ACTION_TARGETS:
        return None, None, (
            jsonify({"error": f"一度に処理できるのは{MAX_FOLLOW_ACTION_TARGETS}件までです"}),
            400,
        )
    return cookie_header, targets, None


def verify_action_applied(session, cookie_header, urlname, method):
    # note.com's follow/unfollow endpoint sometimes answers a processed request
    # with an error-looking status (rate limiting, transient 5xx). Before
    # reporting those as failures, check whether the follow state actually
    # changed as intended.
    if not urlname:
        return False
    try:
        detail = fetch_creator(session, urlname, headers=request_headers(cookie_header))
    except (NoteApiError, requests.RequestException):
        return False
    if detail is None:
        return False
    expected_following = method == "POST"
    return detail.get("isFollowing") == expected_following


def perform_follow_action(cookie_header, targets, method):
    # NOTE: /api/v3/users/{key}/following is not officially documented by note.com.
    # Reverse-engineered from a live captured request: the path segment is the
    # creator's hex "key" (not the numeric "id"), auth is the full note.com
    # cookie jar (session cookie + note_gql_auth_token together), and
    # X-Requested-With: XMLHttpRequest is required or note.com returns 422.
    session = requests.Session()
    headers = {
        **REQUEST_HEADERS,
        "Referer": "https://note.com/",
        "Origin": "https://note.com",
        "X-Requested-With": "XMLHttpRequest",
        "Cookie": cookie_header,
    }

    results = []
    for index, target in enumerate(targets):
        key = target.get("key")
        urlname = target.get("urlname")

        if index > 0:
            time.sleep(FOLLOW_ACTION_DELAY_SECONDS)

        if not key:
            results.append({"urlname": urlname, "success": False, "error": "keyが取得できませんでした"})
            continue

        url = f"{NOTE_FOLLOW_API_BASE}/{key}/following"
        resp = None
        error = None

        try:
            resp = session.request(method, url, headers=headers, timeout=REQUEST_TIMEOUT)
        except requests.RequestException:
            error = "note.comへの接続に失敗しました"

        if error:
            results.append({"urlname": urlname, "success": False, "error": error})
            continue

        if resp.status_code == 429:
            rate_limit_error = "note.comのレート制限に達しました。数分〜数十分単位のクールダウンが必要な場合があるので、5〜10分ほど間隔を空けて件数を減らして試してください"
            if verify_action_applied(session, cookie_header, urlname, method):
                results.append({"urlname": urlname, "success": True, "error": None})
            else:
                results.append({"urlname": urlname, "success": False, "error": rate_limit_error})
            # Once rate-limited, every remaining target will fail the same way.
            # Stop immediately instead of still waiting+trying each one.
            for remaining in targets[index + 1 :]:
                results.append(
                    {"urlname": remaining.get("urlname"), "success": False, "error": rate_limit_error}
                )
            break

        if resp.status_code == 403 and is_cloudfront_block_response(resp):
            # note.com sits behind CloudFront, which starts hard-blocking this
            # server's requests (a generic CloudFront error page, not a
            # note.com-level response) once too many requests land in a short
            # window -- observed after ~20 sequential follow/unfollow calls.
            # Every remaining target would fail the same way, so stop instead
            # of hammering an endpoint that's already blocking us (which only
            # prolongs the block) and dumping the same raw HTML into every row.
            block_error = (
                "note.com側のアクセス制限に達したため、これ以降の処理を中断しました。"
                "30分〜1時間ほど間隔を空けてから、件数を減らして再度お試しください。"
            )
            results.append({"urlname": urlname, "success": False, "error": block_error})
            for remaining in targets[index + 1 :]:
                results.append({"urlname": remaining.get("urlname"), "success": False, "error": block_error})
            break

        if resp.status_code in (401, 403):
            results.append(
                {"urlname": urlname, "success": False, "error": "認証に失敗しました。Cookieが正しいか確認してください"}
            )
            continue

        ok = resp.status_code in (200, 201, 204)
        if not ok:
            ok = verify_action_applied(session, cookie_header, urlname, method)
        results.append(
            {
                "urlname": urlname,
                "success": ok,
                "error": None if ok else f"note.comがstatus {resp.status_code}を返しました",
            }
        )

    return results


@app.post("/api/unfollow")
def unfollow():
    cookie_header, targets, error = parse_follow_action_request()
    if error:
        return error
    return jsonify({"results": perform_follow_action(cookie_header, targets, "DELETE")})


@app.post("/api/follow")
def follow():
    cookie_header, targets, error = parse_follow_action_request()
    if error:
        return error
    return jsonify({"results": perform_follow_action(cookie_header, targets, "POST")})


@app.get("/extension.zip")
def download_extension():
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for root, _dirs, files in os.walk(EXTENSION_DIR):
            for filename in files:
                if filename == ".DS_Store":
                    continue
                file_path = os.path.join(root, filename)
                zip_file.write(file_path, arcname=os.path.relpath(file_path, EXTENSION_DIR))
    buffer.seek(0)
    return send_file(
        buffer,
        mimetype="application/zip",
        as_attachment=True,
        download_name="youmitonde-helper-extension.zip",
    )


@app.get("/")
def index():
    return send_from_directory(app.static_folder, "index.html")


if __name__ == "__main__":
    # Debug mode is kept off on purpose: this process handles the user's note.com
    # session cookie, and Werkzeug's interactive debugger is a known RCE risk.
    app.run(host="127.0.0.1", port=5000, debug=False)
